language: php

php:
  - 8.0
  - 8.1

env:
  - XDEBUG_MODE=coverage

before_script:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpstan analyze
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
